// Ordered (Bayer) dithering. Instead of smooth gradients, a coverage value in
// [0,1] is compared against a per-pixel threshold from a small repeating matrix,
// producing the stippled/halftone look used across the whole scene (mountains,
// orb shading, cloud edges, star twinkle).
//
// The matrix is generated by the standard recursive Bayer construction rather
// than hard-coded, so it's derived, not copied:
//   M(1) = [0]
//   M(2n) = [[4*M(n),     4*M(n)+2],
//            [4*M(n)+3,   4*M(n)+1]]

function buildBayer(size: number): number[] {
  let matrix = [0];
  let n = 1;
  while (n < size) {
    const next: number[] = new Array(n * n * 4);
    const stride = n * 2;
    for (let y = 0; y < n; y++) {
      for (let x = 0; x < n; x++) {
        const v = matrix[y * n + x] * 4;
        next[y * stride + x] = v;
        next[y * stride + x + n] = v + 2;
        next[(y + n) * stride + x] = v + 3;
        next[(y + n) * stride + x + n] = v + 1;
      }
    }
    matrix = next;
    n *= 2;
  }
  return matrix;
}

export const BAYER_SIZE = 8;
export const BAYER = buildBayer(BAYER_SIZE);
const BAYER_MAX = BAYER_SIZE * BAYER_SIZE;

export const BAYER_MATRIX_4X4 = [
  [0, 8, 2, 10],
  [3, 11, 1, 9],
  [15, 7, 13, 5],
  [12, 4, 14, 6],
] as const;

export function getBayerDither(x: number, y: number, intensity: number): boolean {
  return intensity * 16 > BAYER_MATRIX_4X4[y & 3][x & 3];
}

/** Returns true if a pixel at (x, y) should be "on" for the given coverage (0..1). */
export function ditherTest(x: number, y: number, coverage: number): boolean {
  const threshold = (BAYER[(y & 7) * BAYER_SIZE + (x & 7)] + 0.5) / BAYER_MAX;
  return coverage > threshold;
}

/** Maps coverage (0..1) to one of `tones.length` discrete bands with dithered transitions. */
export function ditherBand(x: number, y: number, coverage: number, bandCount: number): number {
  const threshold = (BAYER[(y & 7) * BAYER_SIZE + (x & 7)] + 0.5) / BAYER_MAX;
  const eased = coverage * coverage * (3 - 2 * coverage);
  const banded = eased * bandCount - threshold + 0.5;
  return Math.max(0, Math.min(bandCount - 1, Math.floor(banded)));
}
